// <auto-generated />
namespace LibraryAdmin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialcreate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate3));
        
        string IMigrationMetadata.Id
        {
            get { return "202401061830300_initialcreate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
